CREATE DATABASE IF NOT EXISTS house_db;
USE house_db;

CREATE TABLE IF NOT EXISTS houses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    address VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    rooms INT NOT NULL,
    square_meters DECIMAL(10, 2) NOT NULL
);
